DROP DATABASE IF EXISTS pdfs;
CREATE DATABASE pdfs;
USE pdfs;

CREATE TABLE archivo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    ruta VARCHAR(500) NOT NULL,
    creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
